### ISSUE TITLE
loading classifier error

### ISSUE THREAD

**Issue by marcosly** [bearsprogrammer/real-time-deep-face-recognition#1]
i encounter a error when i running realtime_facenet_git.py:  
""(model, class_names) = pickle.load(infile)
    EOFError

Process finished with exit code 1""
should i retrain my own classifier first ,cause i found out your classifier model is "/my_classifier.pkl'"

**Comment by bearsprogrammer** [comment]
@marcosly Yes, you should run 'Make_classifier_.py' first. and then you will have your own classifier(like my_classifier.pkl). above all things, you need align face data via running 'Make_aligndata.py'.
* I will upload that how to use my code soon.

**Comment by marcosly** [comment]
Thank you for your work! I can now run the the demo successfully,thanks for all of your contributions to the real time face detection and recognition.

**Comment by bearsprogrammer** [comment]
@marcosly That's good news. If you found that any inoperative or need modifying parts of my code, tell me anytime.
