### ISSUE TITLE
Accuracy is very less

### ISSUE THREAD

**Issue by Zumbalamambo** [bearsprogrammer/real-time-deep-face-recognition#3]
I tried this however the accuracy is too low and it jumps. why so?

**Comment by bearsprogrammer** [comment]
@Zumbalamambo I think, your classifier.pkl file is likely to be incomplete. I recently committed[(e4cfc5f)](https://github.com/bearsprogrammer/real-time-deep-face-recogniton/commit/e4cfc5fc9bfaf44d2d9d7556e811a741ea55e0fb) to the Readme.md file about how to use the code. </br>Please refer to this commit and follow it slowly.

**Comment by Gabit07** [comment]
> I tried this however the accuracy is too low and it jumps. why so?

Have you tried to improve accuracy?
