### ISSUE TITLE
难以复现

### ISSUE THREAD

**Issue by Allenstin** [bearsprogrammer/real-time-deep-face-recognition#30]
作者应该是来自中国的大神吧.我想请问下,大神能给下更为详细的操作说明.您目前给的这些内容,让新手复现人脸识别是否难以下手啊.谢谢

**Comment by elbayaninho** [comment]
In english please

**Comment by Allenstin** [comment]
> In english please

I mean, the author gives too little explanation. As a newbie, it is difficult to achieve.I still like to speak Chinese, haha.要是哪天我想在github上写东西,我就只想用中文.最主要原因是英文不好,其次就是不想给外国佬看见.哈哈

**Comment by Allenstin** [comment]
However, now I understand the code, and successfully implemented face recognition.Thanks.

**Comment by Gabit07** [comment]
Hello, can you help me? I am still having a problem to run the code

**Comment by Gabit07** [comment]
> In english please

DId you successfully run the code?

**Comment by Allenstin** [comment]
> > In english please
> 
> DId you successfully run the code?



> Hello, can you help me? I am still having a problem to run the code

What can I do for you?

**Comment by Gabit07** [comment]
> > > In english please
> > 
> > 
> > DId you successfully run the code?
> 
> > Hello, can you help me? I am still having a problem to run the code
> 
> What can I do for you?

I stuck here...
(cv) gabit@gabit-all-series-invalid-entry-length-16-fixed-up-to-11:~/real-time-deep-face-recognition$ sudo python3 Make_classifier_git.py 
2019-03-27 14:59:30.451369: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-27 14:59:30.475526: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2398375000 Hz
2019-03-27 14:59:30.476614: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5541f30 executing computations on platform Host. Devices:
2019-03-27 14:59:30.476640: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Number of classes: 6
Number of images: 0
Loading feature extraction model
Model filename: /home/gabit/real-time-deep-face-recognition/models/20170511-185253.pb
WARNING:tensorflow:From /home/gabit/real-time-deep-face-recognition/facenet.py:377: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
Calculating features for images
Training classifier
Traceback (most recent call last):
  File "Make_classifier_git.py", line 57, in <module>
    model.fit(emb_array, labels)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py", line 149, in fit
    accept_large_sparse=False)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 756, in check_X_y
    estimator=estimator)
  File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 582, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 128)) while a minimum of 1 is required.

**Comment by Gabit07** [comment]
> > > In english please
> > 
> > 
> > DId you successfully run the code?
> 
> > Hello, can you help me? I am still having a problem to run the code
> 
> What can I do for you?

Thank you for your quick reply.
Could you take a look on my code?

**Comment by Allenstin** [comment]
> > > > In english please
> > > 
> > > 
> > > DId you successfully run the code?
> > 
> > 
> > > Hello, can you help me? I am still having a problem to run the code
> > 
> > 
> > What can I do for you?
> 
> Thank you for your quick reply.
> Could you take a look on my code?

I have not encountered this kind of mistake. This code needs to be used in conjunction with 'facenet'. You give me an email, I will send you the previous code.

**Comment by Gabit07** [comment]
> > > > > In english please
> > > > 
> > > > 
> > > > DId you successfully run the code?
> > > 
> > > 
> > > > Hello, can you help me? I am still having a problem to run the code
> > > 
> > > 
> > > What can I do for you?
> > 
> > 
> > Thank you for your quick reply.
> > Could you take a look on my code?
> 
> I have not encountered this kind of mistake. This code needs to be used in conjunction with 'facenet'. You give me an email, I will send you the previous code.

Oh, thank you.
my email is tkgabit@gmail.com

**Comment by Allenstin** [comment]
> > > > > > In english please
> > > > > 
> > > > > 
> > > > > DId you successfully run the code?
> > > > 
> > > > 
> > > > > Hello, can you help me? I am still having a problem to run the code
> > > > 
> > > > 
> > > > What can I do for you?
> > > 
> > > 
> > > Thank you for your quick reply.
> > > Could you take a look on my code?
> > 
> > 
> > I have not encountered this kind of mistake. This code needs to be used in conjunction with 'facenet'. You give me an email, I will send you the previous code.
> 
> Oh, thank you.
> my email is [tkgabit@gmail.com](mailto:tkgabit@gmail.com)

I have sent the entire code to you, please check it out. You only need to change the path and you will be able to run it. I am from China. If you have time to come to China, please remember to contact me. My email is: allenstin@foxmail.com, thank you

**Comment by Gabit07** [comment]
> > > > > > > In english please
> > > > > > 
> > > > > > 
> > > > > > DId you successfully run the code?
> > > > > 
> > > > > 
> > > > > > Hello, can you help me? I am still having a problem to run the code
> > > > > 
> > > > > 
> > > > > What can I do for you?
> > > > 
> > > > 
> > > > Thank you for your quick reply.
> > > > Could you take a look on my code?
> > > 
> > > 
> > > I have not encountered this kind of mistake. This code needs to be used in conjunction with 'facenet'. You give me an email, I will send you the previous code.
> > 
> > 
> > Oh, thank you.
> > my email is [tkgabit@gmail.com](mailto:tkgabit@gmail.com)
> 
> I have sent the entire code to you, please check it out. You only need to change the path and you will be able to run it. I am from China. If you have time to come to China, please remember to contact me. My email is: [allenstin@foxmail.com](mailto:allenstin@foxmail.com), thank you

Okay. I received well with thanks. Yeah, I will let you know if I will go to China.

**Comment by Gabit07** [comment]
> > > > In english please
> > > 
> > > 
> > > DId you successfully run the code?
> > 
> > 
> > > Hello, can you help me? I am still having a problem to run the code
> > 
> > 
> > What can I do for you?
> 
> I stuck here...
> (cv) gabit@gabit-all-series-invalid-entry-length-16-fixed-up-to-11:~/real-time-deep-face-recognition$ sudo python3 Make_classifier_git.py
> 2019-03-27 14:59:30.451369: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-03-27 14:59:30.475526: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2398375000 Hz
> 2019-03-27 14:59:30.476614: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5541f30 executing computations on platform Host. Devices:
> 2019-03-27 14:59:30.476640: I tensorflow/compiler/xla/service/service.cc:158] StreamExecutor device (0): , 
> Number of classes: 6
> Number of images: 0
> Loading feature extraction model
> Model filename: /home/gabit/real-time-deep-face-recognition/models/20170511-185253.pb
> WARNING:tensorflow:From /home/gabit/real-time-deep-face-recognition/facenet.py:377: FastGFile.**init** (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.gfile.GFile.
> Calculating features for images
> Training classifier
> Traceback (most recent call last):
> File "Make_classifier_git.py", line 57, in 
> model.fit(emb_array, labels)
> File "/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py", line 149, in fit
> accept_large_sparse=False)
> File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 756, in check_X_y
> estimator=estimator)
> File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 582, in check_array
> context))
> ValueError: Found array with 0 sample(s) (shape=(0, 128)) while a minimum of 1 is required.

I've solved by myself. The problem was I didn't correctly path images
 with tf.Session() as sess:

        datadir = '/home....

**Comment by Allenstin** [comment]
> > > > > In english please
> > > > 
> > > > 
> > > > DId you successfully run the code?
> > > 
> > > 
> > > > Hello, can you help me? I am still having a problem to run the code
> > > 
> > > 
> > > What can I do for you?
> > 
> > 
> > I stuck here...
> > (cv) gabit@gabit-all-series-invalid-entry-length-16-fixed-up-to-11:~/real-time-deep-face-recognition$ sudo python3 Make_classifier_git.py
> > 2019-03-27 14:59:30.451369: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> > 2019-03-27 14:59:30.475526: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2398375000 Hz
> > 2019-03-27 14:59:30.476614: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5541f30 executing computations on platform Host. Devices:
> > 2019-03-27 14:59:30.476640: I tensorflow/compiler/xla/service/service.cc:158] StreamExecutor device (0): ,
> > Number of classes: 6
> > Number of images: 0
> > Loading feature extraction model
> > Model filename: /home/gabit/real-time-deep-face-recognition/models/20170511-185253.pb
> > WARNING:tensorflow:From /home/gabit/real-time-deep-face-recognition/facenet.py:377: FastGFile.**init** (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.
> > Instructions for updating:
> > Use tf.gfile.GFile.
> > Calculating features for images
> > Training classifier
> > Traceback (most recent call last):
> > File "Make_classifier_git.py", line 57, in
> > model.fit(emb_array, labels)
> > File "/usr/local/lib/python3.5/dist-packages/sklearn/svm/base.py", line 149, in fit
> > accept_large_sparse=False)
> > File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 756, in check_X_y
> > estimator=estimator)
> > File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py", line 582, in check_array
> > context))
> > ValueError: Found array with 0 sample(s) (shape=(0, 128)) while a minimum of 1 is required.
> 
> I've solved by myself. The problem was I didn't correctly path images
> with tf.Session() as sess:
> 
> ```
>     datadir = '/home....
> ```

OK, Congratulations

**Comment by lajihaonange** [comment]
@Allenstin 大佬，你好，我在运行这个程序的时候，发现对于不同的人给出的识别结果都是一样的，请问您能指导我一下怎样对程序改进才能识别出来不同的人脸吗？

**Comment by ccl-private** [comment]
你好，我也是一头雾水，不知道怎么运行，路径怎么设置？我现在就只有一张我自己的图片，下载了21070511-185253的模型，还有det*.npy，可以运行代码吗？能否写个详细的步骤哈～

**Comment by ccl-private** [comment]
ops 我也成功了，放照片的文件夹要按命名来区分，不能所有照片放一个文件夹。而且，最好一个人有多张图像放同一个文件夹。

**Comment by lajihaonange** [comment]
恭喜你啊，其实我建议你去看一下官方的facenet，这个就是在那个基础上完成的，不过官方文档有详细的步骤说明




------------------ 原始邮件 ------------------
发件人: "ccl"<notifications@github.com>; 
发送时间: 2019年8月15日(星期四) 下午4:43
收件人: "bearsprogrammer/real-time-deep-face-recognition"<real-time-deep-face-recognition@noreply.github.com>; 
抄送: "AS"<2775160793@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [bearsprogrammer/real-time-deep-face-recognition] 难以复现 (#30)




ops 我也成功了，放照片的文件夹要按命名来区分，不能所有照片放一个文件夹。而且，最好一个人有多张图像放同一个文件夹。
