### ISSUE TITLE
Result says "0 numbers of images"

### ISSUE THREAD

**Issue by elnasdgreat** [bearsprogrammer/real-time-deep-face-recognition#9]
i have created my data/images folder and edited also the paths in the Make_aligndata_git.py
inside my data/images folder, i put 5 images
e_e_0001.jpg
e_e_0002.jpg
so on..

but after I run Make_aligndata_git.py, it says
"Total number of images: 0"

I checked my output folder, and there are folders with the same number and names of my images..

please help me :(

**Comment by mpena2099** [comment]
Same problem here. :-/

**Comment by so-as** [comment]
when I run this project to do face detect with tensorflow 1.2 version on the ubuntu 14.04, I met the error:
`2017-10-13 00:39:02.833148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Found device 0 with properties: name: Tesla M40 major: 5 minor: 2 memoryClockRate(GHz): 1.112 pciBusID: 0000:82:00.0 totalMemory: 11.93GiB freeMemory: 11.82GiB 2017-10-13 00:39:02.833193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1055] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla M40, pci bus id: 0000:82:00.0, compute capability: 5.2) 2017-10-13 00:39:02.863038: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 11.93G (12808486912 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY`
It seem the 12G memory is not enough for mtcnn model. Could you tell me which GPU device you use, how much memory does the mtcnn detection algorith need?
thank you very much, wait for your reply! @elnasdgreat @mpena2099

**Comment by 1993-tensa-g** [comment]
Same problem here.
working on windows.
I tried debugging little bit, looks like we are not able to get inside  for loop of cls.image_paths in make_alignment.py
If we even just try to print image_paths not able to print those as well.

is there anything wrong with FName_LName_001.png format..?

**Comment by elnasdgreat** [comment]
inside the "data" folder
create folders inside it and name it based on a person's name you want to identify
then inside the folders, place the face images
